### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by Carrot0729** [guoxxxxxxx/picture-download-tools#3]
请问在爬取180张左右的时候就无法再继续下载图片了，这个您有办法解决吗？

**Comment by Carrot0729** [comment]
似乎无法继续的原因是一直在下载同一张照片

**Comment by guoxxxxxxx** [comment]
这个应该多等一会儿就好了，我设置的重试次数为3，每次请求3次，或者你可以手动切换到下一张图片，来跳过当前无法下载的图片。

**Comment by Carrot0729** [comment]
> 这个应该多等一会儿就好了，我设置的重试次数为3，每次请求3次，或者你可以手动切换到下一张图片，来跳过当前无法下载的图片。

请问该如何手动切换呢，是在出现这种情况的时候点击下一张图片就可以了吗？

**Comment by guoxxxxxxx** [comment]
是的，出现这种情况的话，点击下一张图片理论上可以解决这个问题。

**Comment by Carrot0729** [comment]
好的，我发现出现这种情况的原因是浏览器无法继续向下滚动了，谢谢您大佬。
